### ISSUE TITLE
Error while loading shared libraries: libQt5OpenGL.so.5: cannot open shared object file: No such file or directory (Ubuntu 20.04) -> Resolved

### ISSUE THREAD

**Issue by stephanmg** [sreiter/ProMesh#13]
Does one need to install QT5 on Ubuntu? What are the minimal library requirements?

Stephan

**Comment by sreiter** [comment]
Did you download the installer www.promesh3d.com? The required Qt libraries come with ProMesh. Did you install ProMesh using the setup script which comes with the tar.gz package? Or did you just start it directly from the shell? There is no conscious upper bound on supported platforms.

**Comment by stephanmg** [comment]
Ah okay, I just downloaded the `.tar.gz` from there, yes. But I forgot that I need to run the `.sh` scripts.  Thank you @sreiter.

One more comment, is it necessary to use `export` on the LD_LIBRARY_PATH in `ProMesh4.sh`?

It will run fine when instead we invoke ProMesh4 by this in the `ProMesh4.sh` script 

`LD_LIBRARY_PATH=$DIR/.application/lib $DIR/.application/bin/ProMesh4 "$@"`

instead of

```
export LD_LIBRARY_PATH=$DIR/.application/lib 
$DIR/.application/bin/ProMesh4 "$@"
```

Thus the global  LD_LIBRARY_PATH won't be poluted. I just imagine someone having a non-empty LD_LIBRARY_PATH (maybe exported in a `.bashrc` file or elsewhere) then  the LD_LIBRARY_PATH will contain only the ProMesh specific addition, other items are discarded, maybe if the export is necessary prepend `$LD_LIBRARY_PATH` to the LD_LIBRARY_PATH, i.e. maybe add:

`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$DIR/.application/lib"`

Stephan

**Comment by sreiter** [comment]
Since ProMesh starts on Linux using the recommended setup.sh, I will close the issue.
Nevertheless, thanks for your comments. However, if I'm not mistaken, the script which overwrites the LD_LIBRARY_PATH is typically executed in its own process, e.g., by starting ProMesh from the Dock. So typically overwriting the LD_LIBRARY_PATH there hopefully shouldn't be an issue. I agree, that the methods you propsed seem a bit more appropriate. I would recommend to open a new issue once the current behavior actually causes problems to anyone.
Thanks!

**Comment by stephanmg** [comment]
Yeah, this is not a problem, I'm just saying the `export` might not be good to do, as ProMesh starts perfectly without an explicit export statement anyway.

Cheers.
